### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#1]
Просьба добавить README.md в котором есть описание проделанной работы, а также инструкцию по запуску. Также если есть возможность добавить swagger документацию, в которой будет эндпоинт, на который я смогу передать адрес кошелька и получу ответ.

**Comment by xrisent** [comment]
https://github.com/xrisent/tron
Обновил, добавил readme и сделал эндпоинт.
Еще хотел узнать, можно ли поэкспериментировать и добавить сюда бд?

сб, 18 нояб. 2023 г. в 17:09, AZIMBEK SAGYNBAEV ***@***.***>:

**Comment by asagynbaev** [comment]
Спасибо большое, БД не требуется.
