### ISSUE TITLE
Отсутствие асинхронности

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#10]
В файле views.py находятся вызовы всех функций:

`

    balance = int(get_balance(address=address, api_key=api_key))/1000000
    anomaly_value = check_anomaly_value(transactions=transactions, minimum_threshold=TRON_SETTINGS['minimum_threshold'], maximum_threshold=TRON_SETTINGS['maximum_threshold'])
    anomaly_transfers = check_anomaly_transfers(transactions=transactions, difference_time=TRON_SETTINGS['time_difference'], address=address)
    anomaly_hiding = check_anomaly_hiding(transactions=transactions, address=address, time_difference=TRON_SETTINGS['time_difference'], api_key=api_key)
    anomaly_relation = check_relation(address=address, api_key=api_key_chainalysis)

    finalEvaluation = get_finalEvaluation(anomaly_value, anomaly_transfers, anomaly_hiding, anomaly_relation, value_coefficient=TRON_SETTINGS['value_coefficient'], transfers_coefficient=TRON_SETTINGS['transfers_coefficient'], hiding_coefficient=TRON_SETTINGS['hiding_coefficient'], relation_coefficient=TRON_SETTINGS['relation_coefficient'], transactions_len=get_len(address=address, api_key=api_key), balance=balance)

`

Необходимо сделать вызов всех функций асинхронным, дабы снизить время ожидания выполнения всех в ряд. Добавить async await. Если функции будут выполняться асинхронно, то можно сильно снизить время затраченное на выполнение проверки.

finalEvaluation должен быть вызван только после того, как получены ответы от всех предыдущих **асинхронных** функций.

Также учесть, что баланс и нахождение в санкционном списке не являются необходимыми для получения финальной оценки, тоесть их можно не дожидаться.

Про асинхронность можно почитать тут: https://highload.today/asinhronnost-v-python-kak-twitter-obrabatyvaet-milliardy-seansov-v-den/

**Comment by xrisent** [comment]
xrisent

**Comment by asagynbaev** [comment]
Просьба в случае чего, задавать вопросы. И по завершению отписаться.

**Comment by xrisent** [comment]
Я выполнил задание, еще пытался оптимизировать частые и незакономерные движеня средств, но пока не получилось
Сейчас все +- на минуту быстрее
