### ISSUE TITLE
Добавить усолвия в код

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#11]
На этапе ввода адреса, реализовать небольшие проверки:

- Если количество транзакций на кошельке меньше 10, в ответе возвращать: "Адрес содержит менее 10 транзакций, риск минимальный"
- Если находится в санкционном списке, без анализа возвращать: риск 100, и в сообщении: "Адрес находится в санкционном списке OFAC"

**Comment by xrisent** [comment]
Выполнено
