### ISSUE TITLE
Добавить в возвращаемый ответ два поля

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#12]
Необходимо в ответ добавить:

- Дату первой транзакции
- Дату последней транзакции

**Comment by xrisent** [comment]
Выполнено

**Comment by asagynbaev** [comment]
там в ответе реализована вся транзакция целиком, а нужно было только дату и время

**Comment by xrisent** [comment]
а ой, щас сделаю

**Comment by xrisent** [comment]
исправил
