### ISSUE TITLE
Оптимизация кода(рефакторинг)

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#14]
Необходимо оптимизировать метод возвращающий попытки скрыть происхождение средств, метод check_anomaly_hiding

**Comment by xrisent** [comment]
Извиняюсь, в том комментарий я спутал и написал, что пытался оптимизировать частые и незакономерные транзакции, хотя делал это с anomaly_hiding, то есть попытки скрыть происхождение средств

**Comment by asagynbaev** [comment]
#14 Updated!

**Comment by xrisent** [comment]
Оптимизировал, теперь быстрее все на +- 40 сек
