### ISSUE TITLE
Рассмотреть возможность использования библиотеки httpx

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#17]
**httpx** - это библиотека для выполнения асинхронных HTTP-запросов в Python. Она предоставляет возможность делать асинхронные HTTP-запросы в стиле синхронного кода и поддерживает множество возможностей, таких как HTTP/1.1, HTTP/2, WebSocket, и другие.

**httpx** полезен в контексте выполнения асинхронных HTTP-запросов из асинхронного кода, что особенно важно в асинхронных приложениях, таких как приложения Django с асинхронными представлениями.

Так как Django-приложение использует асинхронные представления, и uvicorn использован для запуска приложения, значит мы бы могли использовать httpx в коде для выполнения асинхронных HTTP-запросов.

**Comment by xrisent** [comment]
Добавил, стало чутка быстрее
