### ISSUE TITLE
Некорректный сваггер

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#2]
<img width="1440" alt="image" src="https://github.com/xrisent/tron/assets/29392221/73e2c634-12de-4f5a-8987-b7168a8b3851">

Как на данный эндпоинт передать адрес кошелька? Не был задокументирован процесс создания os.env файла, и названия переменных SECRET, что отняло время на первый запуск...

`На эндпоинт должны быть отправлены данные адреса кошелька, пороговые значения для Z-оценок в одном из тестов, пороговое значение времени в секундах, а также коэффициенты для финального результата`

Какие значения необходимо выставлять? Или какие лучше всего подходят для получения наилучшего результата? Необходимы примерные значения

**Comment by asagynbaev** [comment]
Пользователь вводит только адрес кошелька, остальные входные параметры необходимо вынести в конфигурационный файл .json либо settings.py(на ваше усмотрение) и задать самые подходящие значения.

Также просьба вводмый адрес из body вынести в query, чтоб получилось следующее: /check_address/TG6Udj1YeqXQhr7aSteVf28iWmV1vMtWeA

Метод должен быть GET

**Comment by xrisent** [comment]
Сделал


вс, 19 нояб. 2023 г. в 16:39, AZIMBEK SAGYNBAEV ***@***.***>:
