### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#20]
The conflict is caused by:
    The user requested eth-keys==0.2.4
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
    eth-account 0.5.9 depends on eth-keys<0.4.0 and >=0.3.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by xrisent** [comment]
попробуйте установить eth-account именно 0.4.0

**Comment by asagynbaev** [comment]
Просьба откатить до старой версии, и запушить

**Comment by xrisent** [comment]
Извините, а у вас какая версия python?

**Comment by asagynbaev** [comment]
Python 3.8

**Comment by xrisent** [comment]
Все мои библиотеки заточены под python 3.11, вы же можете обновить python?

**Comment by asagynbaev** [comment]
Обновился до 3.11, по прежнему та же ошибка.

`попробуйте установить eth-account именно 0.4.0` - так и сделаю, закрываю тикет
