### ISSUE TITLE
python 3.11

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#24]
`twisted_iocpsupport/iocpsupport.c:1210:10: fatal error: io.h: No such file or directory
       1210 | #include "io.h"
            |          ^~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for twisted-iocpsupport
ERROR: Could not build wheels for twisted-iocpsupport, which is required to install pyproject.toml-based projects
Successfully built autobahn coreschema openapi-codec parsimonious tronapi trx-utils
Failed to build twisted-iocpsupport`

This error occurs because twisted-iocpsupport is not supported by python 3.11 Consider going back to any versions between 3.6 and 3.10 that fixed the problem for me. Go to twisted-iocpsupport documentation and see the versions of python it supports

**Comment by xrisent** [comment]
Это может возникнуть, потому что у меня другая операционная система, windows
Можете сказать какая у вас операционная система и я постараюсь решить проблему

**Comment by asagynbaev** [comment]
Linux Ubuntu 22.04

**Comment by xrisent** [comment]
Давайте я просто все переделаю под python 3.10

**Comment by asagynbaev** [comment]
Давайте под 3.8

**Comment by xrisent** [comment]
Запустил и проверил на 3.8.10 на локальном сервере, конфликтов вроде нету, проверьте у себя, пожалуйста

**Comment by asagynbaev** [comment]
Решилось путем комментирования строки:
# twisted-iocpsupport==1.0.3
