### ISSUE TITLE
Баг

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#25]
После последних изменений, при проверке адреса, возникает ошибка. Адрес, который я ввожу: TYea94GkpQ5y1XANSscr4QKp5ZAFyYsurw

Текст ошибки:
IndexError at /tron/check_address/TYea94GkpQ5y1XANSscr4QKp5ZAFyYsurw/
list index out of range

<img width="1440" alt="image" src="https://github.com/xrisent/tron/assets/29392221/0b19ea3e-d8d7-4947-afc0-a6898d16b48d">

**Comment by xrisent** [comment]
Исправил, можете проверить
