### ISSUE TITLE
Привести возвращаемый ответ к одному виду

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#27]
Для более легкой обработки ответа, необходимо привести возвращаемый ответ к одному виду:

{
  error: null,
  message: null,
  finalEvaluation = {
          'finalEvaluation': 4,
          'transactions': 12,
          'blacklist': false,
          'balance': 304,
          'first_transaction': 2020-10-12,
          'last_transaction': 2023-08-23
      }
      
В случае, если мы получим ошибку, то в поле error будет текст ошибки, а остальные поля будут null, если сработает какое-то условие, то в поле message мы получим текст, а остальные поля будут пустыми, и так далее.

Статусы кодов необходимо добавить, тоесть:
200 - мы получаем, когда все ок (finalEvaluation=body, error=null, message=null)
230 - когда транзакций меньше 10 (finalEvaluation=null, error=null, message=body)
231 - когда адрес находится в санкционном списке (finalEvaluation=null, error=null, message=body)
400 - bad request (finalEvaluation=null, error=body, message=null)
500 - internal server error (finalEvaluation=null, error=body, message=null)

Привести сваггер в порядок, в соответствии с новыми вводными

**Comment by xrisent** [comment]
А если адрес не найден, то какой код?
И код вставлять в поле error?

**Comment by asagynbaev** [comment]
Адрес всегда будет найден) это же блокчейн) просто он будет как бы "новым", с нулевым балансом, и отсутствием транзакций:)

**Comment by xrisent** [comment]
А, извиняюсь, спасибо большое

Еще хотел уточнить, мне выводить ответ даже если проверка на количество транзакций до сих пор не проведена? просто там есть адреса с >2млн транзакций и пока он проверит, то пройдет вечность

**Comment by asagynbaev** [comment]
На данный момент необходимо ограничиться последними 100 транзакциями... Относительно адресов, превышающих 1000 транзакций будем модифицировать код, внедряя big data.  Кстати, огромная просьба начать изучать данное направление:)

**Comment by xrisent** [comment]
В моем коде уже есть встроенная проверка на метод запроса, мне все равно сделать кастомную? просто тогда в сваггере будет показываться все методы, хотя можно только get
