### ISSUE TITLE
Проверить исправность оценки адреса

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#28]
По адресу TYea94GkpQ5y1XANSscr4QKp5ZAFyYsurw имеется 799 транзакций, для анализа были взяты 25(как указано в настройках), но показал степень риска 0, что не похоже на действительность.

Также, просьба подтвердить, что он для проверки использует последние 25 транзакций.

**Comment by xrisent** [comment]
Проверил, возвращает оценку 8
![image](https://github.com/xrisent/tron/assets/78533056/280cf7ef-961c-458d-80f7-56a962ee7c02)
Также проверяет только 25 транзакций
![image](https://github.com/xrisent/tron/assets/78533056/d6927af2-53a1-4ea1-ad3e-5769a558e91f)
В настройках
![image](https://github.com/xrisent/tron/assets/78533056/a3570f8f-48f5-4e4d-9eeb-0175a0c11ac2)
