### ISSUE TITLE
Отсутствие фильтрации в получении транзакций

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#29]
В файле get_transactions.py, 

`    def format_transactions(response_data):
        for transaction in response_data:
                time = datetime.fromtimestamp(transaction['block_timestamp']/1000)
                data.append({
                    'transaction_id': transaction['transaction_id'],
                    'from': transaction['from'],
                    'to': transaction['to'],
                    'value': transaction['value'],
                    'timestamp': transaction['block_timestamp'],
                    'time': '%s'%time,
                })
    `

отсутвует фильтрация по символу: USDT, необходимо было брать в рассчет только транзакции связанные с тезером

**Comment by xrisent** [comment]
Там в трон уже есть отфильтрованные, я просто давал запрос именно на trc20 транзакции в url.
"https://api.trongrid.io/v1/accounts/{address}/transactions/trc20"

**Comment by asagynbaev** [comment]
Необходимо именно, символ: USDT

**Comment by xrisent** [comment]
Добавил
