### ISSUE TITLE
Получение информации об аккаунте

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#30]
TronScan распологает информацией о том, что адрес является подозрительным. (Пример:  https://tronscan.org/#/address/TJTDPzDy85M7dehAokyTebEAwjPPJfFfFF)

Необходимо каким то образом получать данную информацию, также могут помочь разные форумы.

<img width="1021" alt="image" src="https://github.com/xrisent/tron/assets/29392221/3c0bf010-7744-4a99-b036-2c1e9341ef97">

**Comment by asagynbaev** [comment]
Нашел)))

https://apilist.tronscanapi.com/api/accountv2?address=TJTDPzDy85M7dehAokyTebEAwjPPJfFfFF

<img width="1440" alt="image" src="https://github.com/xrisent/tron/assets/29392221/6f98ea04-8d5f-4122-ae42-8b35905b32f4">

**Comment by asagynbaev** [comment]
Бывает 3 вида адресов: 

- redTag: ""
- redTag: "Suspicious"
- redTag: "Risky"

**Comment by xrisent** [comment]
Нужно в finalEvaluation вытащить это же?

**Comment by asagynbaev** [comment]
ага, добавить в возвращаемый ответ

**Comment by asagynbaev** [comment]
также просьба возвращать ответы на русском языке, там старые тоже на англ., их тоже на русский перевести

**Comment by xrisent** [comment]
Хорошо, сейчас сделаю

**Comment by xrisent** [comment]
Добавил redTag, и вроде перевел все message, проверьте
