### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#31]
`{"finalEvaluation": {"finalEvaluation": 24.83, "transactions": 7111, "blacklist": false, "balance": 0.017064, "first_transaction": "2023-05-25 13:04:00", "last_transaction": "2023-05-28 15:31:09", "redTag": "\u041f\u043e\u0434\u043e\u0437\u0440\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439"}, "error": null, "message": null}`

по результатам последних добавлений в коде, необходимо обратить внимание на кодировку ответа. Кажется необходимо выбрать UTF8. На данный момент установлена Unicode

**Comment by xrisent** [comment]
Он показывает нормально, если формат JSON, а в других форматах он выдает такой redTag, я уже попробовал все варианты, но ничего не работает

**Comment by xrisent** [comment]
Получилось, проверьте
