### ISSUE TITLE
Ответы некоторых сообщений

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#36]
<img width="1099" alt="image" src="https://github.com/xrisent/tron/assets/29392221/6c8a4e84-5425-4ad6-a661-e70d030649b6">

Некоторые ответы все еще содержат некорректную кодировку

**Comment by xrisent** [comment]
а можете адрес скинуть?

**Comment by asagynbaev** [comment]
TPjnc8xCFghALmmoY52krDqnM5UuAUnrMW

**Comment by xrisent** [comment]
Исправил
