### ISSUE TITLE
Неверный ответ по количеству транзакции по адресу

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#37]
Адрес - TZ3aYR6oqVnYhh2M9YxzXDLWEvvJrfz3NV
В ответ получаю, что менее 10 транзакций, но на самом деле их больше(55)

<img width="946" alt="image" src="https://github.com/xrisent/tron/assets/29392221/579c4d24-3cef-4450-865b-fe6595d68961">

**Comment by xrisent** [comment]
Сделал ошибку в коде, извиняюсь, исправил
