### ISSUE TITLE
Расширить ответ

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#4]
Для более четкого понимания результатов анализа, в возвращаемый ответ добавить:

1. Количество транзакций - 34
2. Состоит в санкционном списке OFAC - Да/Нет
3. Оценка риска - 15.6
4. Баланс USDT - 18.2374

Возвращаемый ответ должен выглядеть примерно след. образом:
`{
      "riskScore": 15.6,
      "transactions": 34,
      "blackList": true,
      "balance": 18.2374
}`

**Comment by xrisent** [comment]
Добавить уже к существующим данным или заменить полностью на такой формат?

вс, 19 нояб. 2023 г. в 12:56, AZIMBEK SAGYNBAEV ***@***.***>:

**Comment by asagynbaev** [comment]
Просьба полностью заменить.

**Comment by xrisent** [comment]
Исправил все замечания, проверьте, пожалуйста

вс, 19 нояб. 2023 г. в 13:11, AZIMBEK SAGYNBAEV ***@***.***>:
