### ISSUE TITLE
Баг. Количество транзакций

### ISSUE THREAD

**Issue by asagynbaev** [xrisent/tron#7]
Какой бы не вставил адрес,  количество транзакций всегда 20. "transactions": 20

**Comment by xrisent** [comment]
Изменил лимит на 200

вс, 19 нояб. 2023 г. в 22:07, AZIMBEK SAGYNBAEV ***@***.***>:

**Comment by xrisent** [comment]
Необходимо проверять на аномалии только какую-то часть транзакций в угоду скорости или оставить то, что он будет проверять абсолютно все транзакции адреса?

**Comment by asagynbaev** [comment]
Анализ должен быть полным, независимо от затраченного на это времени

**Comment by xrisent** [comment]
Тогда выполнено
